name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '42 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to lack of activity. It will be closed in 7 days if no activity resumes.'
        stale-pr-message: 'This pull request has been marked as stale due to lack of activity. It will be closed in 7 days if no activity resumes.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
